version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    env_file:
      - ./environment/common.env
  nginx:
    image: nginx:stable
    ports:
      - 8082:80
      - 444:443
    links:
      - php
    volumes_from:
      - php
    env_file:
      - ./environment/common.env
    environment:
      - PROOPH_ENV=development
  php:
    build: .
    volumes:
      - .:/var/www
      - /etc/nginx/conf.d/
    env_file:
      - ./environment/common.env
    depends_on:
      - mysql
      # - postgres
    environment:
      - PROOPH_ENV=development