<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            User\Handler\AllUser::class => User\Handler\AllUserFactory::class,
            User\Handler\AllUserHandler::class => User\Handler\AllUserHandlerFactory::class,
            User\Handler\DeleteUser::class => User\Handler\DeleteUserFactory::class,
            User\Handler\DeleteUserHandler::class => User\Handler\DeleteUserHandlerFactory::class,
            User\Handler\RegisterHandler::class => User\Handler\RegisterHandlerFactory::class,
            User\Handler\ShowUser::class => User\Handler\ShowUserFactory::class,
            User\Handler\ShowUserHandler::class => User\Handler\ShowUserHandlerFactory::class,
            User\Handler\StoreUser::class => User\Handler\StoreUserFactory::class,
            User\Handler\StoreUserHandler::class => User\Handler\StoreUserHandlerFactory::class,
            User\Handler\UpdateUser::class => User\Handler\UpdateUserFactory::class,
            User\Handler\UpdateUserHandler::class => User\Handler\UpdateUserHandlerFactory::class,
        ],
    ],
];
